version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_dashboard
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data5:/var/lib/postgresql/data

  backend:
    build: ./backend  # Path to Django backend
    container_name: django_backend_dashboard
    restart: always
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:8000"

    volumes:
      - ./backend:/app

    command: bash -c ./start.sh

  frontend:
    build: ./front # Path to Angular frontend
    container_name: angular_frontend_dashboard
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./front:/app
    command: sleep infinity

volumes:
  postgres_data5: 
