FROM python:3.12.3

WORKDIR /app

COPY requirements.txt .

# Install system dependencies for PostgreSQL & Pillow
RUN apt-get update 
RUN apt-get install -y 
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
